// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniTodo.Modules.Todos.Infrastructure.Db;

#nullable disable

namespace UniTodo.Modules.Todos.Infrastructure.Db.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260724061114_InitialTodo")]
    partial class InitialTodo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ResetPolicy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ResetsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ownerId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Permissions", "UniTodo.Modules.Todos.Domain.Entities.Run.Permissions#RunPermissions", b1 =>
                        {
                            b1.Property<bool>("MemberAllowedToAddItems")
                                .HasColumnType("bit");

                            b1.Property<bool>("MemberAllowedToChangeDescriptions")
                                .HasColumnType("bit");

                            b1.Property<bool>("MemberAllowedToCompleteUnassignedItems")
                                .HasColumnType("bit");

                            b1.Property<bool>("MemberAllowedToMarkIncompleteUnassignedItems")
                                .HasColumnType("bit");

                            b1.Property<bool>("MemberAllowedToModifyNotesForUnassignedItems")
                                .HasColumnType("bit");

                            b1.Property<bool>("MemberAllowedToRemoveItems")
                                .HasColumnType("bit");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Settings", "UniTodo.Modules.Todos.Domain.Entities.Run.Settings#RunSettings", b1 =>
                        {
                            b1.Property<int>("EndOfWeekDay")
                                .HasColumnType("int");

                            b1.Property<bool>("PreserveHistory")
                                .HasColumnType("bit");

                            b1.Property<string>("TimeZone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("runs");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RunIterationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RunIterationId");

                    b.ToTable("runItems");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunIteration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("runIterations");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "RunId");

                    b.HasIndex("RunId");

                    b.ToTable("runMembers");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.TodoItemTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("TodoListId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId");

                    b.HasIndex("Description", "TodoListId")
                        .IsUnique();

                    b.ToTable("todoItemTemplates");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.TodoListTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ResetPolicy")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("todoLists");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunItem", b =>
                {
                    b.HasOne("UniTodo.Modules.Todos.Domain.Entities.RunIteration", "Iteration")
                        .WithMany("RunItems")
                        .HasForeignKey("RunIterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iteration");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunIteration", b =>
                {
                    b.HasOne("UniTodo.Modules.Todos.Domain.Entities.Run", "Run")
                        .WithMany("Iterations")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunMember", b =>
                {
                    b.HasOne("UniTodo.Modules.Todos.Domain.Entities.Run", "Run")
                        .WithMany("Members")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.TodoItemTemplate", b =>
                {
                    b.HasOne("UniTodo.Modules.Todos.Domain.Entities.TodoListTemplate", "TodoList")
                        .WithMany("TodoItemTemplates")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.Run", b =>
                {
                    b.Navigation("Iterations");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunIteration", b =>
                {
                    b.Navigation("RunItems");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.TodoListTemplate", b =>
                {
                    b.Navigation("TodoItemTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
