// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniTodo.Modules.Todos.Infrastructure.Db;

#nullable disable

namespace UniTodo.Modules.Todos.Infrastructure.Db.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResetPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ResetsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ownerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("runs");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunIterationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunIterationId");

                    b.ToTable("runItems");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunIteration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("runIterations");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RunId");

                    b.HasIndex("RunId");

                    b.ToTable("runMembers");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.TodoItemTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("TodoListId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId");

                    b.HasIndex("Description", "TodoListId")
                        .IsUnique();

                    b.ToTable("todoItemTemplates");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.TodoListTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResetPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("todoLists");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunItem", b =>
                {
                    b.HasOne("UniTodo.Modules.Todos.Domain.Entities.RunIteration", "Iteration")
                        .WithMany("RunItems")
                        .HasForeignKey("RunIterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iteration");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunIteration", b =>
                {
                    b.HasOne("UniTodo.Modules.Todos.Domain.Entities.Run", "Run")
                        .WithMany("Iterations")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunMember", b =>
                {
                    b.HasOne("UniTodo.Modules.Todos.Domain.Entities.Run", "Run")
                        .WithMany("Members")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.TodoItemTemplate", b =>
                {
                    b.HasOne("UniTodo.Modules.Todos.Domain.Entities.TodoListTemplate", "TodoList")
                        .WithMany("TodoItemTemplates")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.Run", b =>
                {
                    b.Navigation("Iterations");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.RunIteration", b =>
                {
                    b.Navigation("RunItems");
                });

            modelBuilder.Entity("UniTodo.Modules.Todos.Domain.Entities.TodoListTemplate", b =>
                {
                    b.Navigation("TodoItemTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
